import { prisma } from '@/lib/prisma'
import { enterprisePortalEnabled } from '@/lib/tenant'
import { requireSchoolAdmin, SchoolAccessError } from '@/lib/org'
import { getSchoolApiContext } from '@/lib/school'
import { z } from 'zod'

const createSchema = z.object({
  name: z.string().min(1).max(80),
  color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
})

function forbidden() {
  return Response.json({ error: 'School admin access required' }, { status: 403 })
}

// GET /api/school/calendars → the org's calendars with event counts.
export async function GET() {
  if (!enterprisePortalEnabled()) return new Response('Not found', { status: 404 })
  try {
    const { tenantScopedOrgId } = await getSchoolApiContext()
    const { org } = await requireSchoolAdmin(tenantScopedOrgId)

    const calendars = await prisma.orgCalendar.findMany({
      where: { organisationId: org.id },
      include: { _count: { select: { events: true } } },
      orderBy: { name: 'asc' },
    })
    return Response.json({ calendars })
  } catch (e) {
    if (e instanceof SchoolAccessError) return forbidden()
    throw e
  }
}

// POST /api/school/calendars → create a calendar (icsToken is generated by Prisma).
export async function POST(req: Request) {
  if (!enterprisePortalEnabled()) return new Response('Not found', { status: 404 })
  try {
    const { tenantScopedOrgId } = await getSchoolApiContext()
    const { org } = await requireSchoolAdmin(tenantScopedOrgId)

    const parsed = createSchema.safeParse(await req.json())
    if (!parsed.success) return Response.json({ error: 'Invalid data' }, { status: 400 })

    try {
      const calendar = await prisma.orgCalendar.create({
        data: { organisationId: org.id, name: parsed.data.name, color: parsed.data.color ?? null },
      })
      return Response.json({ calendar }, { status: 201 })
    } catch (e) {
      if (typeof e === 'object' && e !== null && 'code' in e && (e as { code?: string }).code === 'P2002') {
        return Response.json({ error: 'A calendar with that name already exists.' }, { status: 409 })
      }
      throw e
    }
  } catch (e) {
    if (e instanceof SchoolAccessError) return forbidden()
    throw e
  }
}
